import "./globals.css";
import Header from "@/components/header/page";
import { Spectral_SC, Nunito } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/components/footer/page";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spectralSC = Spectral_SC({ subsets: ["latin"], weight: ["400", "700"] });
const nunito = Nunito({ subsets: ["latin"], weight: ["400", "700"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} ${spectralSC.className}`}>
        <main className="page-wrapper">{children}</main>
        <Footer />
      </body>
    </html>
  );
}